from myproject.ruffwal.raccount.views import *
from myproject.ruffwal.posting.views import *
from myproject.ruffwal.newyear.views import *
from myproject.ruffwal.rsetup.views import *
from myproject.ruffwal.stock.views import *
from myproject.ruffwal.rwreport.views import *
from myproject.ruffwal.recon.views import *
from myproject.ruffwal.rwadmin.views import *
from django.conf.urls.defaults import *
from django.conf import settings
from django.conf.urls.defaults import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    ('^$',welcomecode),
    ('^header/$', header),
    ('^login/$',index),
    ('^unauto/$',unauto),
    ('^welcome/$',welcomecode),
    ('^changepassword/$',changepassword),
    ('^logout/$',logoutuser),
    ('^entersetup/$',entersetupcode),
    ('^rentersetup/$',rentersetupcode),
    ('^entersetupdet/$',entersetupcodedet),
    ('^createacc/$',createacccode),
    ('^getdata/$',getdataccode),
    ('^getsubaccount/$', getsubaccount),
    ('^getstock/$', getstock),
    ('^getdebtor/$', getdebtordia),
    ('^getstaffonloan/$', getstaffonloan),
    ('^getcreditor/$', getcreditor),
    ('^getministore/$', getministore),
    ('^getsubaccountacc/$', getsubaccountacc),
    ('^getaccountdetails/$', getaccountdetails),
    ('^editsubacc/(\d{5})/$', editsubacc),
    ('^editacc/(\d{5})/$', editacc),
    ('^inventory/$', stock),
    ('^editstock/(\d+)/$', editstock),
    ('^receivables/$', receivablesstatus),
    ('^staffonloan/$', staffonloancode),
    ('^editdebtors/(\d+)/$', editdebtors),
    ('^editstaffonloan/(\d+)/$', editstaffonloan),
    ('^payables/$', creditors),
    ('^accajaxcode/$', accajaxcode),
    ('^editpayables/(\d+)/$', editcreditors),
    ('^chatreport/$', chatreport),
    ('^ministore/$', ministorecode),
    ('^editministore/(\d+)/$', editministore),
    ('^studentacc/$', debtorssch),
    ('^editstudentsacc/(\d+)/$', editdebtorssch),
    ('^posting/enterposting/$',enterposting),
    ('^posting/unauto/$',ppounauto),
    ('^posting/wel/$',wels),
    ('^posting/invoice/$',invoice),
    ('^posting/getacc/$',autocomplete),
    ('^posting/getaccinv/$',autocompleteinv),
    ('^posting/getaccbank/$',autocompletebank),
    ('^posting/getaccbanknot/$',autocompletebanknot),
    ('^posting/getaccbankall/$',autocompletebankall),
    ('^posting/getinvoice/$',getinvoice),
    ('^posting/editinvoice/(\d+)/$',editinvoice),
    ('^posting/deleteinvoice/(\d+)/$',deleteinvoice),
    ('^posting/ajax/$',testajax),
    ('^posting/ajaxcode/$',testajaxcode),
    ('^posting/process/$',process),
    ('^posting/receipt/$',receipt),
    ('^posting/getreceipt/$',getreceipt),
    ('^posting/getpayment/$',getpayment),
    ('^posting/getstandard/$',getstandard),
    ('^posting/receiptprocess/$',receiptprocess),
    ('^posting/payment/$',payment),
    ('^posting/paymentajax/$',paymentajax),
    ('^posting/paymentajaxcode/$',paymentajaxcode),
    ('^posting/paymentprocess/$',paymentprocess),
    ('^posting/editpayment/(\d+)/$',editpayment),
    ('^posting/deletepayment/(\d+)/$',deletepayment),
    ('^posting/editreceipt/(\d+)/$',editreceipt),
    ('^posting/deletereceipt/(\d+)/$',deletereceipt),
    ('^posting/generaljournal/$',generaljournal),
    ('^posting/generaljournal2/$',generaljournal2),
    ('^posting/generaljournal1/$',generaljournal1),
    ('^posting/editjournal/(\d+)/$',editjournal),# to delete journal entries
    ('^posting/journalprocess/$',journalprocess),
    ('^posting/standardjournal/$',standardjournal),
    ('^posting/editstandard/(\d+)/$',editstandard),
    ('^posting/deletestandard/(\d+)/$',deletestandard),
    ('^posting/standardprocess/$',stardardprocess),
    ('^posting/verifytrans/$',verifytrans),
    ('^posting/accountsearch/$',accountsearch),
    ('^posting/paymentajaxcodesea/$',paymentajaxcodesea),
    ('^posting/postbill/$',postbill),
    ('^posting/getaccpocket/$',autocompletebankpocket),
    ('^posting/pocketmoney/$',pocketmoney),
    ('^posting/getpocketm/$',getpocketm),
    ('^posting/deletepocket/(\d+)/$',deletepocket),
    ('^posting/pocketprocess/$',pocketprocess),
    ('^posting/oldreceipt/$',printreceipt),
    #REPORT MANAGEMENT
    ('^report/enter/$',enterreport),
    ('^report/chartofacc/$',chartofaccrep),
    ('^report/chartofaccrep/$',chatreport),
    ('^report/receivablerep/$',receivablesrep),
    ('^report/stockrep/$',stockrep),
    ('^report/payablerep/$',payablerep),
    ('^report/ministorerep/$',ministorerep),
    ('^report/trialbalancerep/$',trialbalancerep),
    ('^report/profitlossrep/$',profitlossrep),
    ('^report/balancesheetrep/$',balancesheetrep),
    ('^report/statementrep/$',statementreprep),
    ('^report/statementrepall/$',statementreprepall),
    ('^report/getreportacc/$',autocompletebankallreport),
    ('^report/getministatement/$',getministatement),
    ('^report/getministatementpayable/$',getministatementpayable),
    ('^report/valueadded/$',valueadded),
    ('^report/getsubaccountaccreport/$',getsubaccountaccreport),
    ('^report/unauto/$',reportunauto),
    #STOCK MANAGEMENT
    ('^stock/wel/$',wel),
    ('^stock/unauto/$',stunauto),
    ('^stock/stockenter/$',stockenter),
    ('^stock/newstock/$',newstock),
    ('^stock/getcr/$',autocompletecr),
    ('^stock/getdr/$',autocompletedr),
    ('^stock/getstockadd/$',getstockadd),
    ('^stock/getstockout/$',getstockout),
    ('^stock/issued_ajax/$',stockissuedajax),
    ('^stock/history_ajax/$',stockhistoryajax),
    ('^stock/stock-history/$',stockhistory),
    ('^stock/deletestock/(\d+)/$',deletestock),
    ('^stock/addprocess/$',addprocess),
    ('^stock/outstock/$',outstock),

    ('^stock/stock_issue/$',stock_issue),
    ('^stock/ajaxcodeoutstock/$',autocompleteoutstock),
    ('^stock/ajaxout/$',autocompleteup),
    ('^stock/ajaxcodeout/$',autocompleteout),
    ('^stock/deletestockout/(\d+)/$',deletestockout),
    ('^stock/outprocess/$',outprocess),
    ('^stock/statement/$',statementrep),
    ('^stock/ajaxcodestate/$',ajaxcodestate),

  #RECONCILIATION
    ('^recon/enterrec/$',enterrec),
    ('^recon/unauto/$',reconunauto),
    ('^recon/statement/$',reconstatement),
    ('^recon/unpresented/$',unpresented),
    ('^recon/ajax/$',autocompleterecon),
    ('^recon/ajaxall/$',recontestajaxall),
    ('^recon/getpresented/$',getpresented),
    ('^recon/getcredited/$',getcredited),
    ('^recon/editunpresented/(\d+)/$',editunpresented),
    ('^recon/uncredited/$',uncredited),
    ('^recon/ajaxalluncr/$',ajaxalluncr),
    ('^recon/edituncredited/(\d+)/$',edituncredited),
    ('^recon/unpresentedsta/$',unpresentedsta),
    ('^recon/uncreditedsta/$',uncreditedsta),
    #TEMPORARY POSTING
    ('^newyear/enterposting/$',tempenterposting),
    ('^newyear/unauto/$',temppounauto),
    ('^newyear/invoice/$',tempinvoice),
    ('^newyear/getinvoicenewyear/$',getinvoicenewyear),
    ('^newyear/getreceiptnewyear/$',getreceiptnewyear),
    ('^newyear/getpaymentnewyear/$',getpaymentnewyear),
    ('^newyear/editinvoice/(\d+)/$',tempeditinvoice),
    ('^newyear/deleteinvoice/(\d+)/$',tempdeleteinvoice),
    ('^newyear/ajax/$',temptestajax),
    ('^newyear/ajaxcode/$',temptestajaxcode),
    ('^newyear/process/$',tempprocess),
    ('^newyear/receipt/$',tempreceipt),
    ('^newyear/receiptprocess/$',tempreceiptprocess),
    ('^newyear/payment/$',temppayment),
    ('^newyear/paymentajax/$',temppaymentajax),
    ('^newyear/paymentajaxcode/$',temppaymentajaxcode),
    ('^newyear/paymentprocess/$',temppaymentprocess),
    ('^newyear/editpayment/(\d+)/$',tempeditpayment),
    ('^newyear/deletepayment/(\d+)/$',tempdeletepayment),
    ('^newyear/editreceipt/(\d+)/$',tempeditreceipt),
    ('^newyear/deletereceipt/(\d+)/$',tempdeletereceipt),
    ('^newyear/generaljournal/$',tempgeneraljournal),
    ('^newyear/generaljournal2/$',tempgeneraljournal2),
    ('^newyear/generaljournal1/$',tempgeneraljournal1),
    ('^newyear/editjournal/(\d+)/$',tempeditjournal),# to delete journal entries
    ('^newyear/journalprocess/$',tempjournalprocess),
    ('^newyear/standardjournal/$',tempstandardjournal),
    ('^newyear/editstandard/(\d+)/$',tempeditstandard),
    ('^newyear/deletestandard/(\d+)/$',tempdeletestandard),
    ('^newyear/standardprocess/$',tempstardardprocess),
    ('^newyear/verifytrans/$',tempverifytrans),
    ('^newyear/accountsearch/$',tempaccountsearch),
    ('^newyear/paymentajaxcodesea/$',temppaymentajaxcodesea),
    ('^newyear/oldreceipt/$',tempprintreceipt),
    url(r'^assets/', include('myproject.ruffwal.asset.urls')),
    url(r'^budget/', include('myproject.ruffwal.budget.urls')),
    url(r'^sysadmin/', include('myproject.ruffwal.rwadmin.urls')),
    #SYSTEM ADMIN
    (r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT}),
)
